### ISSUE TITLE
why I used web3.py connection node error

### ISSUE THREAD

**Issue by ztlovemst11** [MyEtherWallet/myetherapi#5]
from web3 import Web3,HTTPProvider
from eth_utils import decode_hex,encode_hex
my_provider = HTTPProvider('https://api.myetherapi.com/eth')
w13 = Web3(my_provider)
addr = "0x520C03a35F3344C10F823C0c811B44DBa74Ba23B"
a = w13.eth.getBalance(addr)
print(a)

error：ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:720)

what happened？

**Comment by eosclassicteam** [comment]
@ztlovemst11 They moved their api endpoint to https://api.myetherwallet.com/eth

**Comment by ztlovemst11** [comment]
thanks，it‘s ok
